use_frameworks!

platform :ios, '10.0'

target 'FGCallKit_Example' do
  pod 'FGCallKit', :path => '../'
  
  pod 'AFNetworking', '4.0.1'
  pod 'xpjsip', '2.12.1'

  target 'FGCallKit_Tests' do
    inherit! :search_paths

    
  end
end
